** Path

global raw="Your path/Stranded_Occupations_Replication/Data/raw"
global temp="Your path/Stranded_Occupations_Replication/Data/temp"
global use="Your path/Stranded_Occupations_Replication/Data/use"

cd "$temp"



/*Note: Execute data_preparation first, followed by data_analysis, in the prescribed sequence of each script. There is no need to manage file storage manually, as datasets not required for preservation will be cleared automatically.*/


**** Data Analysis
*###.  Fig. 1. /*======================================================*/

//Fig. 1A is generated by python script fig1


//Fig. 1B is generated by python script fig1

//Fig. 1C 
use "$temp/strandind_new_ocu", clear
graph hbar proportion_nostr if  proportion_nostr > 0.95, ///Top 10 fossil fuel occupations with the highest prevalence in non-fossil fuel industries. 0.95 is the cutoff value for the top 10.
    over(Occupationtitle, sort(1) descending) /// Grouping: Occupational type
    bar(1, fcolor(lavender) ) ///
    ylabel(, nogrid) ///
    nofill  


///Fig. 1D 
use "$temp/strandind_new_ocu", clear
graph hbar strand_emrate if  strand_emrate > 0.39 , ///Top 10 most concentrated fossil fuel occupations.0.39 is the cutoff value for the top 10.
    over(Occupationtitle, sort(1) descending) /// Grouping: Occupational type
    bar(1, fcolor(lavender) ) ///
    ylabel(, nogrid) ///
    nofill    
	

	
*###.  Fig. 2. /*======================================================*/
//Fig. 2A left

use "$temp/jskill_pa.dta", clear //
drop if skill_similarity==1
set scheme  s2color
twoway (kdensity skill_similarity if strandind_new_ocu==1 ), ///
  ylabel(, nogrid) ///
	ytitle("Density") ///
	xlabel(0.2(0.1)1) ///
	xtitle("Skill similarity") //
 
clear all

// Fig. 2B is generated by Python script fig2

/* Fig. 2C is generated using "$use/fig2cl.xlsx" and "$use/fig2cr.xlsx",
   by the Python script fig2 */

/*Fig. 2D */
use "$temp/simocc_851", clear
drop if occupation_code_match==475043 // Remove matched occupation "Roof bolters, mining" 
* 1. Calculate the number of matched occupations for each occupation_code 
bysort type_skill_all occupation_code: gen match_count = _N

* 2. Remove duplicates
duplicates drop type_skill_all occupation_code, force

* 3. Compute the mean values grouped by occupational type
tabstat match_count, by(type_skill_all) stat(mean)
/*
  type_skill_all |      Mean
-----------------+----------
Non-Routine Cogn |  17.93578
Non-Routine Manu |  5.894737
Routine Cognitiv |  8.578947
  Routine Manual |  10.12587
-----------------+----------
           Total |  12.43042
----------------------------

*/
clear all

use "$temp/simocc_81", clear
drop if occupation_code_match==475043 // Remove matched occupation "Roof bolters, mining" 

* 1. Calculate the number of matched occupations for each occupation_code 
bysort type_skill_all occupation_code: gen match_count = _N

* 2. Remove duplicates
duplicates drop type_skill_all occupation_code, force

* 3. Compute the mean values grouped by occupational type
tabstat match_count, by(type_skill_all) stat(mean)
/*

  type_skill_all |      Mean
-----------------+----------
Non-Routine Cogn |  92.09917
Non-Routine Manu |    46.875
Routine Cognitiv |  75.76316
  Routine Manual |   63.4269
-----------------+----------
           Total |  73.42938
----------------------------
*/
clear all 
 
*###.  Fig. 3. /*======================================================*/

// Fig. 3A is plotted using the fig3.ipynb
/* Export "$temp/fig3b_81no.xlsx" and generate the figure with the Python script fig3 */

// Fig. 3B is plotted using the fig3.ipynb
/* Export "$temp/fig3b_81.xlsx" and generate the figure with the Python script fig3 */

*###.  Fig. 4. /*======================================================*/
//Fig. 4 is plotted using the Python script fig4
  
*###.  Fig. 5. /*======================================================*/
//Fig. 5 is plotted using the Python script fig5
  

*###.  Supplementary figure /*======================================================*/

//Supplementary figure 1 
//Top 3 most concentrated occupations in fossil fuel industries by occupational type
use  "$temp/strandind_new_ocu",clear
graph hbar strand_emrate if  strand_emrate > 0.086 & nrc == 1, /// For NRC, the cutoff value is 0.086
    over(Occupationtitle, sort(1) descending) /// 
    bar(1, fcolor(lavender) ) ///
    aspectratio(0.6) ///
    ylabel(, nogrid) ///
    nofill 
graph export "$temp/sp1a.svg", as(svg) name("Graph") replace // Export SVG figure for composition in Adobe Illustrator
	   
graph hbar strand_emrate if  strand_emrate > 0.05 & rc == 1, /// For RC, the cutoff value is 0.05
    over(Occupationtitle, sort(1) descending) /// 
    bar(1, fcolor(lavender) ) ///
    aspectratio(0.6) ///
    ylabel(, nogrid) ///
    nofill 
graph export "$temp/sp1b.svg", as(svg) name("Graph") replace 
	   
graph hbar strand_emrate if  strand_emrate > 0.01 & nrm == 1, /// For NRM, the cutoff value is 0.01
    over(Occupationtitle, sort(1) descending) /// 
    bar(1, fcolor(lavender) ) ///
    aspectratio(0.6) ///
    ylabel(, nogrid) ///
    nofill 
graph export "$temp/sp1c.svg", as(svg) name("Graph") replace 
	   	
graph hbar strand_emrate if  strand_emrate > 0.61 & rm == 1, /// For RM, the cutoff value is 0.61
    over(Occupationtitle, sort(1) descending) /// 
    bar(1, fcolor(lavender) ) ///
    aspectratio(0.6) ///
    ylabel(, nogrid) ///
    nofill  
graph export "$temp/sp1d.svg", as(svg) name("Graph") replace 


   	
//Supplementary figure 4 
//gas plant operators
 use "$temp/simocc_851",clear
keep if occupation_code==518092 //20 six-digit matched occupations.
clear all 

 use "$temp/simocc_81",clear
keep if occupation_code==518092 //100 six-digit matched occupations 
clear all 




